### PR TITLE
Restructure project. Fix PyPI issue

### LINKED ISSUE #3: PyPI package install doesn't work
Using `pip install dashing` will install only the `dist-info`, making the package unusable.

This behavior is the same with both Python 3.7 and 2.7.

### PR DESCRIPTION
**Pull request by Aareon**
Fixes #3

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
@Aareon thanks for the PR. Can you please update the PR to move the files (git mv or create + git rm)?

**Comment by Aareon** [comment]
I just saw your comment @FedericoCeratto. I’ll get on this ASAP

**Comment by FedericoCeratto** [comment]
Thanks!

**Comment by FedericoCeratto** [comment]
(I had to squash the commits, please pull)

**Pull request merged**
